---
namespace: azimuth_cloud
name: terraform
version: 0.1.0
description: Infrastructure provisioning and inventory population using Terraform.
readme: README.md
tags:
  - "infrastructure"
authors:
  - "Matt Pryor <matt@stackhpc.com>"
license:
  - "Apache-2.0"
repository: "https://github.com/azimuth-cloud/ansible-collection-terraform"

dependencies:
  community.general: ">=7.0.0"
