# Acceptable Terraform versions. If a binary fulfilling these criteria is not found,
# terraform_version_max will be downloaded.
# v1.5.5 is the latest version available under the MPL license:
# https://www.hashicorp.com/license-faq#products-covered-by-bsl
terraform_version_min: 1.5.5
terraform_version_max: 1.5.5

# The OS variant and architecture to use
terraform_os: "{{ ansible_system | lower }}"
terraform_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
# The name of the Terraform zip
terraform_zip_name: terraform_{{ terraform_version_max }}_{{ terraform_os }}_{{ terraform_architecture }}.zip
# The URL of the Terraform binary
terraform_binary_url: https://releases.hashicorp.com/terraform/{{ terraform_version_max }}/{{ terraform_zip_name }}

# The directory to put the Terraform binary in if we download it
terraform_binary_directory: /usr/local/bin

# List of directories to search for a suitable Terraform
# By default, search the binary directory + the directories in the path
terraform_additional_search_directories: "{{ lookup('ansible.builtin.env', 'PATH') | split(':') | list }}"
terraform_search_directories: "{{ ([terraform_binary_directory] + terraform_additional_search_directories) | unique }}"

# Become root when downloading Terraform binary
terraform_download_binary_become: false
