---
# The path to the Terraform binary, if not in the PATH
terraform_binary_path:

# If true, the state from the last deploy is used rather than provisioning
terraform_readonly: false

# By default, provision the infrastructure rather than tear it down
terraform_state: present

# Default to the local backend if not otherwise specified
terraform_backend_type: local
# The backend configuration to use
terraform_backend_config: {}
# The variables to use when invoking Terraform
terraform_variables: {}

# The gateway user defaults to the regular SSH user
cluster_gateway_user: "{{ cluster_ssh_user }}"

# Adopt infrastructure into the in-memory inventory
terraform_adopt_inventory: true

# Disable checks for force_path_style s3 option
terraform_disable_s3_force_path_style_checks: false

# If set to true, taint and rebuild the Terraform infrastructure.
terraform_rebuild_nodes: false
