---

- name: Look up floating ip
  os_floating_ip_info:
    floating_ip: "{{ os_floating_ip_id }}"
  register: os_floating_ip_info_result

- name: Set floating IP facts
  set_fact:
    os_floating_ip_info: "{{ os_floating_ip_info_result.floating_ip }}"
