---

- name: Write backend configuration
  copy:
    content: |
      terraform {
        backend "{{ terraform_backend_type }}" { }
      }
    dest: "{{ terraform_project_path }}/backend.tf"

- name: Provision infrastructure using Terraform
  terraform:
    binary_path: "{{ terraform_binary_path or omit }}"
    project_path: "{{ terraform_project_path }}"
    state: "{{ terraform_state }}"
    backend_config: "{{ terraform_backend_config }}"
    force_init: yes
    init_reconfigure: yes
    variables: "{{ terraform_variables }}"
  register: terraform_provision

- name: Populate in-memory inventory
  include_tasks: inventory_adopt.yml
  when: 
    - terraform_state == 'present'
    - terraform_adopt_inventory
